const products=[
 {id:1,name:'Soundcore Life Q20i Headphones',category:'Electronics',price:2499,old:3999,rating:4.5,reviews:'2,341',emoji:'🎧',bg:'#eff2ff',badge:'BESTSELLER',kind:'Featured'},
 {id:2,name:'Nova X Pro Smartphone',category:'Mobiles',price:18999,old:24999,rating:4.4,reviews:'1,829',emoji:'📱',bg:'#f1efff',badge:'TRENDING',kind:'Trending'},
 {id:3,name:'Everyday Canvas Tote',category:'Fashion',price:699,old:1299,rating:4.7,reviews:'843',emoji:'👜',bg:'#fff3ea',badge:'UNDER ₹999',kind:'Under ₹999'},
 {id:4,name:'Ceramic Pour-over Set',category:'Home',price:1199,old:1799,rating:4.8,reviews:'512',emoji:'☕',bg:'#f8f2e9',badge:'TOP RATED',kind:'Top rated'},
 {id:5,name:'Pulse Mini Bluetooth Speaker',category:'Electronics',price:1499,old:2299,rating:4.3,reviews:'1,206',emoji:'🔊',bg:'#eef6f4',badge:'JUST IN',kind:'Featured'},
 {id:6,name:'Cloud Knit Everyday Sneakers',category:'Fashion',price:1799,old:2999,rating:4.6,reviews:'975',emoji:'👟',bg:'#f2f3ee',badge:'TRENDING',kind:'Trending'},
 {id:7,name:'Glow & Go Skincare Kit',category:'Beauty',price:849,old:1399,rating:4.5,reviews:'667',emoji:'🧴',bg:'#f9eff1',badge:'UNDER ₹999',kind:'Under ₹999'},
 {id:8,name:'Minimal Desk Lamp',category:'Home',price:999,old:1599,rating:4.8,reviews:'432',emoji:'💡',bg:'#fff7e9',badge:'TOP RATED',kind:'Top rated'}
];
let activeCategory='All',activeFilter='Featured',searchTerm='',sortMode='featured',cart=JSON.parse(localStorage.getItem('shopkart-cart')||'{}');
const grid=document.getElementById('product-grid'),toast=document.getElementById('toast');
const money=n=>'₹'+n.toLocaleString('en-IN');
function shownProducts(){let list=products.filter(p=>(activeCategory==='All'||p.category===activeCategory)&&(!searchTerm||`${p.name} ${p.category}`.toLowerCase().includes(searchTerm))&&(activeFilter==='Featured'?true:activeFilter==='Trending'?p.kind==='Trending':activeFilter==='Under ₹999'?p.price<1000:activeFilter==='Top rated'?p.rating>=4.7:true));if(sortMode==='price-low')list.sort((a,b)=>a.price-b.price);if(sortMode==='price-high')list.sort((a,b)=>b.price-a.price);if(sortMode==='rating')list.sort((a,b)=>b.rating-a.rating);return list}
function renderProducts(){const list=shownProducts();grid.innerHTML=list.length?list.map(p=>`<article class="product-card"><div class="product-visual" style="background:${p.bg}"><span class="product-badge ${p.kind==='Trending'?'hot':''}">${p.badge}</span><button class="wish-btn" data-wish="${p.id}" aria-label="Add ${p.name} to wishlist">♡</button><span class="visual-emoji">${p.emoji}</span></div><div class="product-info"><span class="product-category">${p.category}</span><h3 title="${p.name}">${p.name}</h3><div><span class="rating">★ ${p.rating}</span><span class="rating-count">(${p.reviews})</span></div><div class="price-row"><span class="price">${money(p.price)}</span><span class="old-price">${money(p.old)}</span><span class="discount">${Math.round((1-p.price/p.old)*100)}% off</span></div></div><button class="add-btn" data-add="${p.id}">+ Add</button></article>`).join(''):`<div class="no-results"><h3>No finds just yet</h3><p>Try a different search or category.</p></div>`}
function notify(message){toast.textContent=message;toast.classList.add('show');clearTimeout(notify.timer);notify.timer=setTimeout(()=>toast.classList.remove('show'),2200)}
function saveCart(){localStorage.setItem('shopkart-cart',JSON.stringify(cart));renderCart()}
function countCart(){return Object.values(cart).reduce((sum,n)=>sum+n,0)}
function renderCart(){const count=countCart(),items=Object.entries(cart).filter(([,n])=>n>0);document.getElementById('cart-count').textContent=count;document.getElementById('drawer-count').textContent=`(${count} item${count===1?'':'s'})`;document.getElementById('cart-empty').style.display=items.length?'none':'block';document.getElementById('cart-footer').style.display=items.length?'block':'none';const subtotal=items.reduce((sum,[id,n])=>sum+products.find(p=>p.id===Number(id)).price*n,0);document.getElementById('cart-subtotal').textContent=money(subtotal);document.getElementById('cart-items').innerHTML=items.map(([id,n])=>{const p=products.find(x=>x.id===Number(id));return `<div class="cart-item"><div class="cart-item-visual" style="background:${p.bg}">${p.emoji}</div><div class="cart-item-copy"><b>${p.name}</b><p>${p.category}</p><strong>${money(p.price)}</strong><div class="quantity"><button data-qty="${p.id}" data-delta="-1" aria-label="Decrease quantity">−</button><span>${n}</span><button data-qty="${p.id}" data-delta="1" aria-label="Increase quantity">+</button></div></div><button class="remove-item" data-remove="${p.id}">Remove</button></div>`}).join('')}
grid.addEventListener('click',e=>{const add=e.target.closest('[data-add]');if(add){const id=add.dataset.add;cart[id]=(cart[id]||0)+1;saveCart();notify('Added to your bag ✓')}const wish=e.target.closest('[data-wish]');if(wish){wish.classList.toggle('liked');wish.textContent=wish.classList.contains('liked')?'♥':'♡';notify(wish.classList.contains('liked')?'Saved to your wishlist':'Removed from wishlist')}});
document.querySelectorAll('.category').forEach(button=>button.addEventListener('click',()=>{document.querySelector('.category.active')?.classList.remove('active');button.classList.add('active');activeCategory=button.dataset.category;renderProducts()}));
document.querySelectorAll('.chip').forEach(button=>button.addEventListener('click',()=>{document.querySelector('.chip.selected')?.classList.remove('selected');button.classList.add('selected');activeFilter=button.dataset.filter;renderProducts()}));
document.getElementById('search-form').addEventListener('submit',e=>{e.preventDefault();searchTerm=document.getElementById('search-input').value.trim().toLowerCase();activeFilter='Featured';document.querySelectorAll('.chip').forEach(x=>x.classList.toggle('selected',x.dataset.filter==='Featured'));renderProducts();document.getElementById('products')?.scrollIntoView({behavior:'smooth'})});
document.getElementById('search-input').addEventListener('input',e=>{searchTerm=e.target.value.trim().toLowerCase();renderProducts()});
document.getElementById('sort-select').addEventListener('change',e=>{sortMode=e.target.value;renderProducts()});
document.getElementById('shop-now').addEventListener('click',()=>document.querySelector('.deals').scrollIntoView({behavior:'smooth'}));document.getElementById('view-all').addEventListener('click',()=>{activeCategory='All';activeFilter='Featured';searchTerm='';document.getElementById('search-input').value='';document.querySelectorAll('.category').forEach(x=>x.classList.toggle('active',x.dataset.category==='All'));document.querySelectorAll('.chip').forEach(x=>x.classList.toggle('selected',x.dataset.filter==='Featured'));renderProducts()});
const backdrop=document.getElementById('modal-backdrop');document.getElementById('cart-open').addEventListener('click',()=>backdrop.classList.add('open'));document.getElementById('cart-close').addEventListener('click',()=>backdrop.classList.remove('open'));backdrop.addEventListener('click',e=>{if(e.target===backdrop)backdrop.classList.remove('open')});document.getElementById('continue-shopping').addEventListener('click',()=>backdrop.classList.remove('open'));document.getElementById('cart-items').addEventListener('click',e=>{const quantity=e.target.closest('[data-qty]'),remove=e.target.closest('[data-remove]');if(quantity){const id=quantity.dataset.qty;cart[id]=Math.max(0,(cart[id]||0)+Number(quantity.dataset.delta));if(!cart[id])delete cart[id];saveCart()}if(remove){delete cart[remove.dataset.remove];saveCart()}});
document.getElementById('checkout-btn').addEventListener('click',()=>notify('Checkout is coming soon!'));document.getElementById('login-btn').addEventListener('click',()=>notify('Sign-in is coming soon!'));document.getElementById('newsletter-form').addEventListener('submit',e=>{e.preventDefault();notify('You’re on the list. Look out for good finds!');e.target.reset()});document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();document.getElementById('search-input').focus()}if(e.key==='Escape')backdrop.classList.remove('open')});
renderProducts();renderCart();

